src/FactorGraphTypes.jl

This PR is to replace old IIF code that was used to initially create DFG.  A few extra functions have been included for DFG, but not tested in this context.  Relates to packing and unpacking of factor and variable nodes.

Overwrite versionitis, use latest IIF code

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/GraphsDFG/services/GraphsDFG.jl
test/cloudGraphsDFGTests.jl
test/interfaceTests.jl
test/runtests.jl

This addresses the difference in the new API vs. the prior IncrementalInference API. The two should match now.
Issues addressed:
* #40

ls() and lsf() return symbols rather than full variables/factors

---

src/LightGraphsDFG/LightGraphsDFG.jl
src/LightGraphsDFG/services/LightGraphsDFG.jl

PR For discussion @GearsAD @dehann
Currently Dense `Union{Nothing, Symbol}`
```
@time getAdjacencyMatrix(dfg)
0.000129 seconds (757 allocations: 87.281 KiB)
```
Working with spare matrix as Adjacency Matrix
```
@time exp_getAdjacencyMatrix(dfg)
0.000013 seconds (11 allocations: 1.531 KiB)
```
```julia
23×23 SparseArrays.SparseMatrixCSC{Int64,Int64} with 48 stored entries:
[11,  1]  =  1
[11,  2]  =  1
⋮
[9 , 23]  =  1
[20, 23]  =  1
```
Navigation type factor graphs adjacency will mostly be very sparse 
1. Should sparse matrices (or maybe adjacency lists if symbols are used) be used throughout DFG getAdjacencyMatrix
2. How do we want to handle labels. 
- Sparse internal id (`Int`) sparse matrix with a map for the `Int`s <-> labels. 
- Sparse label matrix
- List of adjacent labels 
- …

Sparse Int Adjacency matrix

---

Project.toml
docs/src/func_ref.md
src/CloudGraphsDFG/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/DistributedFactorGraphs.jl
src/GraphsDFG/GraphsDFG.jl
src/GraphsDFG/services/GraphsDFG.jl
src/MetaGraphsDFG/MetaGraphsDFG.jl
test/FileDFG.jl
test/interfaceTests.jl
test/runtests.jl

The DataFrame adjacency matrix functionality isn't really used and it adds complexity so removing for 0.4 release.
Ref: #101

Removing DataFrame references

---

src/LightDFG/entities/LightDFG.jl
src/LightDFG/services/LightDFG.jl
src/MetaGraphsDFG/entities/MetaGraphsDFG.jl
src/MetaGraphsDFG/services/MetaGraphsDFG.jl
src/SymbolDFG/entities/SymbolDFG.jl
src/SymbolDFG/services/SymbolDFG.jl
test/interfaceTests.jl

Clearer depreciation error in Meta, Symbol, and Light DFG for direct field access on nodeCounter and labelDict
Hopefully clears #111 up a bit.
Fixes #121, if it should be fixed?

Clearer depreciation error in Symbol and Light DFG

---

Project.toml

will be needed by zeptodoctor for auto-merging.  Also note new compat syntax coming:
JuliaLang/Pkg.jl#1454

add upper bounds to Project.toml

---

src/DistributedFactorGraphs.jl
src/services/AbstractDFG.jl

WARNING: using LightGraphs.AbstractGraph in module IncrementalInference conflicts with an existing identifier.
WARNING: using LightGraphs.maximum_adjacency_visit in module IncrementalInference conflicts with an existing identifier.
WARNING: using LightGraphs.strongly_connected_components in module IncrementalInference conflicts with an existing identifier.
WARNING: using LightGraphs.connected_components in module IncrementalInference conflicts with an existing identifier.
WARNING: using LightGraphs.Edge in module IncrementalInference conflicts with an existing identifier.
WARNING: using LightGraphs.dijkstra_shortest_paths in module IncrementalInference conflicts with an existing identifier.
WARNING: using LightGraphs.maximal_cliques in module IncrementalInference conflicts with an …

remove LigthGraphs from DFG.jl to avoid conflicts in IIF

---

Project.toml
src/DistributedFactorGraphs.jl
src/FileDFG/services/FileDFG.jl

- without folder in path
- unique load folder path when many processes are running
closes #344

fix save load DFG issues 344

---

.travis.yml

Test should always be run and kept in tact otherwise there is no point of testing as the coverage drops from 85% to 50%

Don't allow failures on IIF tests

---

src/BigData/services/AbstractBigDataEntries.jl
src/DistributedFactorGraphs.jl

add hasDataEntry, rm ReturnTypes

---

src/FileDFG/services/FileDFG.jl
src/services/AbstractDFG.jl
test/testBlocks.jl

I was busy here in `julia/base/abstractarray.jl`.  Something about `length(dfg) = 1` might be the problem, however, `add=+; add.(1,[2;3])` works fine while `length(::Int)==1` is always true... 
```julia
function copyto!(dest::AbstractArray, src)
destiter = eachindex(dest)
y = iterate(destiter)
count = 0
for x in src
@show count += 1
@show typeof(y)
y === nothing &&
throw(ArgumentError("destination has fewer elements than required"))
dest[y[1]] = x
y = iterate(destiter, y[2])
end
return dest
end
```

add broadcasting

---

src/Deprecated.jl

Hi @Affie ,  just a request that we please stick to proper deprecation cycles since there are downstream issues which cannot be untangled with consistent testing without doing deprecation rounds.  In this case tests in RoME are not able to jump to DFG v0.8.0 cleanly without this.

Update Deprecated.jl * Symbol

---

test/runtests.jl

This was not changed back when 0.8 was tagged.

Use correct IIF branch

---

src/Deprecated.jl
src/services/DFGVariable.jl

bandaid on updateVariableSolverData!

---

src/DistributedFactorGraphs.jl

Temporary fix for #554
This is not really a good idea. It looks like new updates to Pkg might provide a better solution.
Note that ENV variable DFG_USE_CGDFG should be seen as a permanent feature setting as CGDF will be precompiled into the cache.

Precompile CGDFG based on ENV variable

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CommonFunctions.jl
src/Deprecated.jl
src/entities/DFGVariable.jl
src/services/DFGVariable.jl
src/services/Serialization.jl
test/testBlocks.jl

solverKey -> solveKey, fix #599

---

src/services/Serialization.jl

Robust regex+function for cleaning up ZonedTimestamps from Neo4J and other places where it experiences formatting alchemy.
For a test, try this:
```julia
using TimeZones
s = [
"2020-08-12T12:00Z",  #Johan's test case
"2020-08-11T04:05:59-04:00",
"2020-08-11T04:05:59Z",
"2020-08-11T04:05:59.8-04:00",
"2020-08-11T04:05:59.82-04:00",
"2020-08-11T04:05:59.820-04:00",
"2020-08-11T04:05:59.8201-04:00"]
function _fixSubseconds(a)
length(a) == 4 && return a[1:3]*".000"*a[4]
frac = a[5:length(a)-1]
frac = length(frac) > 3 ? frac[1:3] : frac*'0'^(3-length(frac))
return a[1:4]*frac*a[length(a)]
end
function getStandardZDTString(stringTimestamp::String)
ts = replace(stringTimestamp, r"T(\d\d):(\d\d)(Z|z|\+|-)" => s"T\1:\2:00.000\3")
return replace(ts, r":\d\d(\.\d+)?(Z|z|\+|-)" => _fixSubseconds)
end …
```

Robust ZonedTimestamp fixer

---

src/Deprecated.jl
src/services/Serialization.jl

Put back some deprecated for a bit longer and backward compat for loadDFG

---

src/DistributedFactorGraphs.jl
src/entities/DFGFactor.jl

also dropped the `<: Function` inheritance.

add AbstractFactor and AbstractPackedFactor

---

src/DistributedFactorGraphs.jl
src/services/DFGVariable.jl
test/runtests.jl
test/testBlocks.jl
test/test_defVariable.jl

- preparation for more manifold stuff
- functions moved here from iif
- add `getPointType`

Cleanup defVariable and add getPointType

---

Project.toml
src/services/CompareUtils.jl

labeling as workaround, since comparing through a mountain of lambda functions in the new general IIF factor gradients calculation is a bit much for basic comparisons.  Still checking all the previous fields.

fix required for IIF tests with new gradients

---

Project.toml
src/LightDFG/services/LightDFG.jl

Hi, @Affie  @GearsAD , just a heads up -- I'm busy cleaning up code as I see things.  On forced return types, its better to force the return statement itself if needed (not the whole function).  It's especially bad if the whole function return is forced to a non-concrete type.

drop bad (forced) function level return types

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CommonFunctions.jl
src/DistributedFactorGraphs.jl
src/services/Serialization.jl

Base64 encoding the factor as part of CGDFG.

Resolving 833 with the workaround.

---

src/Neo4jDFG/services/Neo4jDFG.jl
src/entities/DFGFactor.jl
src/services/Serialization.jl
test/testBlocks.jl

Neo4jDFG `pack / unpackFactor` not consolidated with `AbstractDFG` (#834).  Factor `solverData` still packed for Neo4jDFG driver as
```julia
props["data"] = base64encode(JSON2.write(convert(PackedFunctionNodeData{P}, getSolverData(fct)))
```
Everyone else should now have factor packed data as top level only `JSON.write` (i.e. just once at the top).
This PR requires that `PackedFactor__` structs are defined with keyword constructors, as used by new `NamedTuple` style marshaling during unpack of JSON2 objects.  In other words, JSON2 is used to unpack factor data without a target type, and therefore returns a `Base.NamedTuple` (great solution for unordered JSON fields).  This allows/now requires DFG to use keyword constructors for all `<:AbstractPackedFactor`.  Easiest way to do so is …

top level JSON2.write only, distr are JSON

---

Project.toml

ManifoldsBase upgrade is not a breaking change in DFG, so only adding to compat
replace and close #871 
replace and close #880

Bump v0.18.4, ManifoldsBase and DocStringExtensions compat

---

src/services/DFGVariable.jl
test/testBlocks.jl

~~not sure if getLabel works if DFGVariable has no solverData.  It should, yet the tests are failing???~~ Was a overly specific test, and is now updated to pass on better error message

Better error message on getSolverData

---

Project.toml
src/DataBlobs/entities/AbstractDataEntries.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/GraphsDFG/entities/GraphsDFG.jl
src/entities/DFGVariable.jl
src/services/Serialization.jl

Note, I added a temporary compat for DFG 18 to DFG 19 on userLabel (old userId), etc.  Dont expect this to interfere since the new keyword constructor arguments are unchanged (userLabel, robotLabel, sessionLabel):
- https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/pull/949/files#diff-6f263d9fe5b4a1795bc09ea6ce3d1107b700b1c0bd60245a8ec4092b91e17fe5R49-R60
Note this PR also drops the Unmarshal.jl dependency.

Fix constructor CI bug, JL1.9, drop Unmarshal, and more

---

Project.toml
src/services/Serialization.jl

PPEs are missing because of a spelling mistake. Adding this as a hotfix.
Reference:
```
"label" => "x0", "dataEntry" => "{}", "nstime" => "0", "dataEntryType" => "{}", "ppeDict" => "{\"default\":{\"solveKey\":\"test\",\"suggested\":[1.0,2.0,3.0],\"max\":[4.0,5.0,6.0],\"mean\":[7.0,8.0,9.0],\"lastUpdatedTimestamp\":\"2023-02-17T23:10:17.982\"}}", "solverDataDict" => "{\"parametric\":...
```

Hotfix for PPE serialization - these are missing in the cloud v3

---

src/Common.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/GraphsDFG/FactorGraphs/FactorGraphs.jl
src/GraphsDFG/services/GraphsDFG.jl
src/services/AbstractDFG.jl
src/services/CommonAccessors.jl
src/services/DFGVariable.jl
test/iifInterfaceTests.jl
test/testBlocks.jl

remove all return types and deprecate lsfWho
