JuliaRobotics/DistributedFactorGraphs.jl

.travis.yml
Project.toml
src/LightGraphsDFG/entities/LightGraphsDFG.jl
src/LightGraphsDFG/services/LightGraphsDFG.jl

it is now passed to the MetaGraphs dict :label
nodeCounter just returs the number of nodes nv(G)

Option with removed nodeCounter and labelDict

---

.travis.yml
README.md

looks like codecov is used in the rest of caesar, is both needed?

add codecov badge

---

Project.toml
src/LightGraphsDFG/services/LightGraphsDFG.jl
src/services/AbstractDFG.jl
test/HexagonalLightGraphs.jl
test/runtests.jl

getSubGraphAroundNode from LightGraphsDFG to AbstractDFG

getSubGraphAroundNode conversions

---

src/DFGPlots/DFGPlots.jl
src/DistributedFactorGraphs.jl

Draft of how to add #78
Tested with lighgraphdfg, clouddfg, and graphdfg.

Add GraphPlot.jl plots Issue #78

---

src/NeedsAHome.jl

add features from IIF

---

src/GraphsDFG/services/GraphsDFG.jl
test/interfaceTests.jl

This is a resolution for: 
* https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/95

Hotfix: v0.3.2 orderingissue

---

src/Common.jl

more ls for types

---

src/Common.jl

- Backport of additional ls functions

FEATURE backport lsWho, lsfWho

---

docs/src/variable_factor_serialization.md
src/DistributedFactorGraphs.jl
src/FileDFG/services/FileDFG.jl
src/services/DFGFactor.jl
src/services/DFGVariable.jl

Provides `packVariable`, `packFactor`, `unpackVariable`, and `unpackFactor` to users for serialization/deserialization.

General variable+factor packing and unpacking functions for DFG

---

src/entities/DFGVariable.jl

Still an abstract type but at least it is not Any.
The changes to make it fully parametric will take longer to do with a depreciation cycle.

Towards #149 - Slightly improved without breaking changes.

---

.travis.yml
Project.toml
test/obsolete_nowinRoME/cloudGraphsDFGTests.jl
test/runtests.jl

- Adds Neo4j for testing
- Adds Travis tests for IIF

Trying IIFTest without direct dependency

---

src/Common.jl
src/DistributedFactorGraphs.jl
src/LightDFG/LightDFG.jl
src/LightDFG/services/LightDFG.jl
src/MetaGraphsDFG/services/MetaGraphsDFG.jl
src/SymbolDFG/SymbolDFG.jl
src/SymbolDFG/services/SymbolDFG.jl
src/entities/DFGVariable.jl
src/services/AbstractDFG.jl
src/services/DFGVariable.jl
test/LightDFGSummaryTypes.jl
test/iifInterfaceTests.jl
test/interfaceTests.jl

- EstimateDict, 
- softtype, 
- type->ppetype, 
- getData->solverData, 
- _getDuplicatedEmptyDFG, 
- labelDict->exist

Include softtype and VariableEstimate changes and bugfixes

---

.travis.yml
Project.toml
src/CloudGraphsDFG/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CGStructure.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CommonFunctions.jl
src/Common.jl
src/DistributedFactorGraphs.jl
src/FileDFG/services/FileDFG.jl
src/LightDFG/LightDFG.jl
src/LightDFG/services/LightDFG.jl
src/MetaGraphsDFG/services/MetaGraphsDFG.jl
src/SymbolDFG/SymbolDFG.jl
src/SymbolDFG/services/SymbolDFG.jl
src/entities/DFGVariable.jl
src/services/AbstractDFG.jl
src/services/DFGVariable.jl
test/LightDFGSummaryTypes.jl
test/iifInterfaceTests.jl
test/interfaceTests.jl
test/runtests.jl

- Backport of the CloudGraphsDFG code and iifInterfaceTests.jl
- Should still function against IIF 0.7.9

Backport of the CGDFG code and unit tests

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/DistributedFactorGraphs.jl
src/entities/DFGVariable.jl
src/services/DFGVariable.jl
test/LightDFGSummaryTypes.jl
test/iifInterfaceTests.jl
test/interfaceTests.jl

Closes #147 
Closes #158 replace pr with new design
Closes #148 replace pr with new design
**Note**
Just the struct so far, TODO integrate, testing, compare, etc.

Closes #147 PointParametricEst implementation

---

Project.toml
README.md
src/CloudGraphsDFG/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CGStructure.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CommonFunctions.jl
test/CGStructureTests.jl
test/iifInterfaceTests.jl
test/runtests.jl
test/sandbox.jl

- Gets, sets, and lists for sessions, robots, and users
- Gets and sets for user, robot, and session data

Additional functionality for graph sentinels

---

src/entities/DFGVariable.jl
test/LightDFGSummaryTypes.jl
test/iifInterfaceTests.jl
test/interfaceTests.jl

Adding `suggested` to the structure.

Additional field in MeanMaxPPE

---

Project.toml

Updates per zeptobot

---

README.md

Go here to see an example:
https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/readme/4Q19/tablulate/README.md

table of badges for readme

---

test/CGStructureTests.jl
test/runtests.jl
test/solveTest.jl

Separating out the solve test from CGStructure.jl. Not a perfect refactor, but improvement on the existing mishmash. More coverage needed on CGDFG in near future.

Small refactor to unblock 0.5.2

---

.travis.yml
src/BigData/entities/AbstractBigDataEntries.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/CommonAccessors.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/entities/DFGFactor.jl
src/entities/DFGVariable.jl
src/services/AbstractDFG.jl
src/services/DFGVariable.jl
test/LightDFGSummaryTypes.jl
test/attic/HexagonalCloud.jl
test/iifInterfaceTests.jl
test/interfaceTests.jl

estimateDict -> ppeDict and deprecation warns

---

src/DFGPlots/DFGPlots.jl
src/DistributedFactorGraphs.jl
src/GraphsDFG/services/GraphsDFG.jl
src/LightDFG/entities/LightDFG.jl
src/SymbolDFG/services/SymbolDFG.jl
src/needsahome.jl
src/services/AbstractDFG.jl
test/interfaceTests.jl

Abstract getSubgraphAroundNode

---

src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CGStructure.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/DistributedFactorGraphs.jl
src/FileDFG/services/FileDFG.jl
src/services/AbstractDFG.jl
src/services/DFGFactor.jl
src/services/DFGVariable.jl

This should be merged before 1Q20/cgdfg_ppes should be merged.

Cleanup on packing and unpacking

---

src/services/CompareUtils.jl

these `@debug`s causes travis to error with maximum log length error. Fix #293

Fix for travis maximum log exceeded in iif

---

src/CommonAccessors.jl
src/entities/DFGFactor.jl

warn on set and get fncargvID field

Start deprecate on field fncargvID #288

---

src/FileDFG/services/FileDFG.jl
src/services/CompareUtils.jl
test/fileDFGTests.jl

Fixing tar file saving, comparator for Graphs.jl, and the FileDFG tests

---

src/needsahome.jl
src/services/CommonAccessors.jl
src/services/DFGVariable.jl
test/testBlocks.jl

[feature] setTimestamp!(dfg, lbl, ts) 

---

src/FileDFG/services/FileDFG.jl

re-add keyword in saveDFG with deprecation

---

attic/sandbox.jl
src/LightDFG/services/LightDFG.jl
src/services/AbstractDFG.jl
test/iifInterfaceTests.jl
test/interfaceTests.jl
test/testBlocks.jl

* Copy into graph changed variable order
* add test and @error on orphans as orphans needs tlc
* iif tests also, hate that test are stil not completely consolidated

[BugFix] Copy into graph changed variable order (#337)

---

src/FileDFG/services/FileDFG.jl
src/entities/DFGFactor.jl

save multihypo,

---

src/services/AbstractDFG.jl

attempt fix for 279

---

src/DistributedFactorGraphs.jl
src/needsahome.jl

better printing api,

---

.travis.yml
docs/src/GraphData.md
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/needsahome.jl
src/services/DFGVariable.jl
test/LightDFGSummaryTypes.jl
test/fileDFGTests.jl
test/iifInterfaceTests.jl
test/testBlocks.jl

fix integration tests 354

---

src/services/DFGVariable.jl
test/iifInterfaceTests.jl
test/testBlocks.jl

need for JuliaRobotics/IncrementalInference.jl#506

update solver data by field and test

---

.travis.yml
Project.toml
src/DFGPlots/DFGPlots.jl
src/LightDFG/services/LightDFG.jl
src/services/AbstractDFG.jl
test/testBlocks.jl

Implement separate variables and factors parameters from #373 
- Also temporary removed arm tests
- bump version

copyGraph separate variables factors

---

src/DistributedFactorGraphs.jl
src/services/AbstractDFG.jl
test/testBlocks.jl

Feature ls2 close #332

---

.travis.yml

Restore arm tests

---

README.md

@GearsAD, note 4.0 does not work

Update readme with correct neo4j version

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CommonFunctions.jl
src/Deprecated.jl
src/GraphsDFG/services/GraphsDFG.jl
src/services/Serialization.jl
test/testBlocks.jl

CGDFG and GraphsDFG fix for #375 and `factor.data` usage

---

src/DistributedFactorGraphs.jl
src/GraphsDFG/GraphsDFG.jl
src/GraphsDFG/services/GraphsDFG.jl
src/services/AbstractDFG.jl
test/iifInterfaceTests.jl

DFG should now be independent of Graphs.jl to remove it completely.

Change GraphsDFG to module

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
test/consolInterfaceDev.jl
test/runtests.jl
test/testBlocks.jl
test/testFurther.jl

FIX CGDFG addFactor! errors but adds factor

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/services/AbstractDFG.jl
test/runtests.jl

Also needs the updated IIF code

Fixing cloud solving functions

---

src/BigData/services/AbstractBigDataEntries.jl
src/DistributedFactorGraphs.jl

addDataEntry!,

---

.travis.yml
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/entities/DFGFactor.jl
src/services/Serialization.jl
test/consolInterfaceDev.jl
test/interfaceTests.jl
test/runtests.jl
test/testBlocks.jl

Note: neo4j  tests not working on arm64

Standardize and test cloud graph variable and factor crud

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
test/consolInterfaceDev.jl
test/runtests.jl
test/testBlocks.jl

updatePPE! standard and bugfix, close #397

Update cgdfg test and fixing bugs

---

src/services/AbstractDFG.jl
test/consolInterfaceDev.jl
test/testBlocks.jl

Some automatic session ids see #415 and tests @GearsAD (to help with the discussion)

Update cgdfg tests and small bugfixes

---

.travis.yml

only certain branches for build pushed  branches

Update .travis.yml to only build on certain pushed branches

---

test/testBlocks.jl

Test more todot orders

---

src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CGStructure.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
test/consolInterfaceDev.jl
test/testBlocks.jl

- Merge after #416. 
- Includes #394 so closing that PR.

CG Structure updates and creating sentinel nodes in the constructor

---

.travis.yml
test/runtests.jl

SKIP_CGDFG_TESTS env var

---

test/runtests.jl

close #378 if downstream is correct

put back CGDFG solve test

---

src/DistributedFactorGraphs.jl
src/entities/DFGFactor.jl
src/services/CompareUtils.jl
test/testBlocks.jl

see https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/issues/274#issuecomment-619189932

step to rename FactorOperationalMemory

---

src/BigData/services/AbstractBigDataEntries.jl
src/DistributedFactorGraphs.jl

close #392 ,  see discussion at #403

fetchData and docs

---

src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
src/entities/DFGFactor.jl
src/services/AbstractDFG.jl
src/services/CompareUtils.jl
src/services/Serialization.jl
test/DataStoreTests.jl
test/compareTests.jl
test/consolInterfaceDev.jl
test/needsahomeTests.jl
test/plottingTest.jl
test/runtests.jl
test/testBlocks.jl

Maintenance on GenericFunctionNodeData types

---

src/Deprecated.jl
src/FileDFG/services/FileDFG.jl
src/services/AbstractDFG.jl
src/services/CompareUtils.jl
test/consolInterfaceDev.jl
test/testBlocks.jl

convenience buildSubgraph, fix #441

---

attic/GraphsDFG/entities/GraphsDFG.jl
src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/FileDFG/services/FileDFG.jl
src/LightDFG/entities/LightDFG.jl
src/entities/AbstractDFG.jl
src/services/AbstractDFG.jl
src/services/Serialization.jl
test/CGStructureTests.jl
test/IIF4DoorsTests.jl
test/consolInterfaceDev.jl
test/fileDFGTests.jl
test/iifInterfaceTests.jl
test/runtests.jl
test/testBlocks.jl
test/testFurther.jl

Also dispach on solverData type for rebuildFactorMetadata!

---

attic/GraphsDFG/entities/GraphsDFG.jl
src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/FileDFG/services/FileDFG.jl
src/LightDFG/entities/LightDFG.jl
src/entities/AbstractDFG.jl
src/services/AbstractDFG.jl
src/services/Serialization.jl
test/CGStructureTests.jl
test/IIF4DoorsTests.jl
test/consolInterfaceDev.jl
test/fileDFGTests.jl
test/iifInterfaceTests.jl
test/runtests.jl
test/testBlocks.jl
test/testFurther.jl

Reverts JuliaRobotics/DistributedFactorGraphs.jl#449
Tests missed a bug

Revert "Also dispach on solverData type for rebuildFactorMetadata!"

---

src/Deprecated.jl
src/LightDFG/services/LightDFG.jl
src/entities/AbstractDFG.jl
src/entities/DFGFactor.jl
src/entities/DFGVariable.jl
src/services/CommonAccessors.jl
src/services/CompareUtils.jl
src/services/DFGFactor.jl
src/services/DFGVariable.jl
src/services/Serialization.jl
test/LightDFGSummaryTypes.jl
test/iifInterfaceTests.jl
test/testBlocks.jl

#328 without the GraphsDFG updates
merge #449 first

Remove _internalId 

---

src/Deprecated.jl

In stead of @deprecate buildSubgraphFromLabels! ...
close #446

leave full buildSubgraphFromLabels! in deprecated, as its not compatable

---

src/Deprecated.jl

missing export

---

src/Deprecated.jl

buildSubgraphFromLabels!: rather error with notes of replacement functions

---

src/DistributedFactorGraphs.jl
src/services/AbstractDFG.jl
test/testBlocks.jl

Fix #458 and testing xref #442 
cc @dehann

buildSubgraph fix and testing 

---

src/LightDFG/services/LightDFG.jl
test/testBlocks.jl

validate variable order on updateFactor!

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/DistributedFactorGraphs.jl
src/services/Serialization.jl

Remove get/setSerializationModule and always use Main

---

src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
src/DFGPlots/DFGPlots.jl
src/LightDFG/FactorGraphs/FactorGraphs.jl

My html is very rusty and from the stone age, but its perhaps a start to better data visualization. From juno `show` example

html DFG plotting on display

---

src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/Deprecated.jl
src/LightDFG/entities/LightDFG.jl
src/LightDFG/services/LightDFG.jl
src/services/DFGVariable.jl
test/CGStructureTests.jl
test/LightDFGSummaryTypes.jl
test/iifInterfaceTests.jl
test/needsahomeTests.jl
test/runtests.jl
test/testBlocks.jl
test/testFurther.jl

standardise to solverParams

---

src/entities/DFGFactor.jl
src/entities/DFGVariable.jl
src/services/AbstractDFG.jl
src/services/DFGFactor.jl
src/services/DFGVariable.jl
src/services/Serialization.jl
test/interfaceTests.jl
test/testBlocks.jl

Feature add nanosecond time to DFGVariable and DFGFactor

---

src/CloudGraphsDFG/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CommonFunctions.jl
src/Common.jl
src/DistributedFactorGraphs.jl
test/interfaceTests.jl
test/runtests.jl
test/testBlocks.jl

~~- [ ] still needs some cleanup~~ Going to do this in separate PR with test improvements

move cgdfg to a module in dfg

---

src/Common.jl
src/DistributedFactorGraphs.jl
src/services/AbstractDFG.jl

see derivative issues #487, #488

getVariableLabelNumber, findFactorsBetweenNaive

---

src/Deprecated.jl
src/FileDFG/services/FileDFG.jl

help with #494 cases

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl

If we have more issues with this we should revisit it.

Fixing CGDFG escaping issue #521

---

docs/Project.toml
docs/src/BuildingGraphs.md
docs/src/DrawingGraphs.md

Docs examples

---

src/BigData/BigData.jl
src/BigData/entities/AbstractBigDataEntries.jl
src/BigData/entities/InMemoryDataStore.jl
src/BigData/services/AbstractBigDataEntries.jl
src/BigData/services/AbstractDataStore.jl
src/BigData/services/FileDataStore.jl
src/BigData/services/InMemoryDataStore.jl
src/CloudGraphsDFG/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CommonFunctions.jl
src/Common.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/entities/AbstractDFG.jl
src/entities/DFGVariable.jl
src/services/DFGVariable.jl
src/services/Serialization.jl
test/DataStoreTests.jl
test/LightDFGSummaryTypes.jl
test/consol_BigDataTests.jl
test/consol_DataEntryBlobTests.jl
test/fileDFGTests.jl
test/iifInterfaceTests.jl
test/interfaceTests.jl
test/runtests.jl
test/testBlocks.jl

- close #403 : rename Elements->Blob
- BigData -> Data

BigData rename

---

src/LightDFG/services/LightDFG.jl
test/testBlocks.jl

Hotfix for lsf with tags filter and test 

---

Project.toml
src/LightDFG/services/LightDFG.jl
test/testBlocks.jl

hotfix for lsf with tags filter and test close #528

---

src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/entities/DFGFactor.jl
src/services/DFGFactor.jl
test/testBlocks.jl

Update as per #533

---

Project.toml
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/entities/DFGFactor.jl
src/entities/DFGVariable.jl
src/services/AbstractDFG.jl
src/services/CommonAccessors.jl
src/services/DFGFactor.jl
src/services/DFGVariable.jl
src/services/Serialization.jl
test/LightDFGSummaryTypes.jl
test/interfaceTests.jl
test/runtests.jl
test/testBlocks.jl

Change DateTime to ZonedDateTime

---

src/LightDFG/entities/LightDFG.jl

Remove params deprecation

---

src/Deprecated.jl
src/services/DFGVariable.jl

Fix add- update- VariableSolverData and PPE deprecation

---

src/services/DFGVariable.jl

Revert getSofttype to return in full

---

attic/InMemoryDataStore.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/entities/DFGVariable.jl
src/services/AbstractDFG.jl
src/services/DFGVariable.jl
src/services/Serialization.jl
test/interfaceTests.jl
test/testBlocks.jl

Small Data Types and in-memory CRUD

---

src/DataBlobs/services/BlobStores.jl
src/DataBlobs/services/FileDataEntryBlob.jl
test/consol_DataEntryBlobTests.jl

Make directory if it doesn't exist with @info

---

src/services/Serialization.jl
test/testBlocks.jl

Fix for non-millisecond timestamps

---

src/CloudGraphsDFG/CloudGraphsDFG.jl
src/CloudGraphsDFG/entities/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/CloudGraphsDFG/services/CommonFunctions.jl
src/DataBlobs/services/BlobStores.jl
src/DataBlobs/services/InMemoryDataEntryBlob.jl
src/DistributedFactorGraphs.jl
src/services/AbstractDFG.jl
test/interfaceTests.jl
test/testBlocks.jl

External DataEntry nodes in CGDFG.

CGDFG blobs as nodes

---

src/Deprecated.jl
src/entities/DFGFactor.jl
src/entities/DFGVariable.jl
src/services/DFGFactor.jl
test/testBlocks.jl

Deleting v0.10 deprecations

---

src/services/Serialization.jl

Bit hacky, split it to find BlobStoreEntry in DistributedFactorGraphs

Split DistributedFactorGraphs.BlobStoreEntry

---

src/DistributedFactorGraphs.jl
src/FileDFG/services/FileDFG.jl
test/fileDFGTests.jl

allow both saveDFG argument orders,

---

src/Deprecated.jl

proper deprecation listSolvekeys,

---

attic/DataStoreTests.jl
docs/src/func_ref.md
src/DataBlobs/DataBlobs.jl
src/DataBlobs/services/AbstractDataEntries.jl
src/DataBlobs/services/DataEntryBlob.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
test/runtests.jl

Fix docs and cleanup deprecated

---

src/services/DFGVariable.jl

change updateVariableSolverData message

---

Project.toml
docs/src/BuildingGraphs.md
docs/src/DrawingGraphs.md
docs/src/GraphData.md
src/FileDFG/services/FileDFG.jl
test/CGStructureTests.jl
test/fileDFGTests.jl
test/iifInterfaceTests.jl
test/solveTest.jl
test/testFurther.jl

for upstream addVariable! deprecation

addVariable! labels->tags

---

src/DataBlobs/services/DataEntryBlob.jl

List all methods for data CRUD in docs

---

src/services/DFGVariable.jl

Also maxlog 1 for updateVariableSolverData!

Allow documenting struct in @defVariable

---

test/fileDFGTests.jl
test/interfaceTests.jl

Update tests for IIF#862

---

src/services/AbstractDFG.jl
test/testBlocks.jl

Regex filter for solve keys in listSolveKeys

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/Deprecated.jl
src/LightDFG/services/LightDFG.jl
src/services/DFGVariable.jl

Add warn_if_absent to update verbs

---

Project.toml
src/CloudGraphsDFG/services/CloudGraphsDFG.jl
src/Deprecated.jl
src/LightDFG/services/LightDFG.jl
src/services/AbstractDFG.jl
src/services/DFGVariable.jl
test/fileDFGTests.jl
test/interfaceTests.jl
test/testBlocks.jl

Best to first finish and then merge this after tests finish:

v0.10.2-rc1

---

src/services/Serialization.jl

Minifix for serialization

---

Project.toml
src/CloudGraphsDFG/services/CommonFunctions.jl
src/Common.jl
src/DistributedFactorGraphs.jl
src/services/Serialization.jl

restore PackedType convert functions

---

src/Common.jl

not strictly required, but came out of #668 work.

convertStructType for ::UnionAll too

---

Project.toml
src/services/Serialization.jl

deserialize vartype{T} fix #671

---

src/services/DFGFactor.jl
test/testBlocks.jl

Use dispatch for isPrior to allow overloading

---

Project.toml
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/services/DFGVariable.jl
test/testBlocks.jl

close https://github.com/JuliaRobotics/IncrementalInference.jl/issues/973 
bump v0.10.7

getXxxPPE --> getPPEXxx 

---

Project.toml
src/DFGPlots/DFGPlots.jl
src/DistributedFactorGraphs.jl
src/services/AbstractDFG.jl
src/services/CustomPrinting.jl
test/interfaceTests.jl
test/testBlocks.jl

show Variable and listSolveKeys

---

src/CloudGraphsDFG/services/CloudGraphsDFG.jl

Not the most elegant solution, may be other places that need fixing, but I need this is master as soon as possible. Please let me know if there are similar issues causing any trouble.

Fixing listVariable and listFactor with regex

---

.travis.yml

Following same strategy as used in JuliaRobotics/ApproxManifoldProducts.jl#82

Fix PkgServer sync issue

---

src/services/DFGVariable.jl

Change to DefaultOrthogonalBasis and add as arg

---

test/attic/HexagonalCloud.jl
test/attic/HexagonalLightGraphs.jl
test/attic/IIF4DoorsTests.jl
test/iifCompareTests.jl
test/solveTest.jl
test/testFurther.jl

relates to JuliaRobotics/IncrementalInference.jl#1381

solveTree! returns only tree

---

Project.toml

The following commits were accidentally pushed to main branch by mistake, so testing here:
- 1ab04d3
- 39a1dd4

bump v0.17.0

---

Project.toml
src/DataBlobs/services/AbstractDataEntries.jl
src/Deprecated.jl
src/DistributedFactorGraphs.jl
src/LightDFG/services/LightDFG.jl

new feature listDataEntrySequence

---

src/CloudGraphsDFG/services/CommonFunctions.jl
src/services/Serialization.jl

preparation for:
- JuliaRobotics/IncrementalInference.jl#1424
- JuliaRobotics/IncrementalInference.jl#1466

refactor _packSolverData

---

src/DistributedFactorGraphs.jl
src/services/Serialization.jl
test/testBlocks.jl

Towards closing JuliaRobotics/IncrementalInference.jl#1424

switch to reconstFactorData

---

docs/Project.toml
docs/src/BuildingGraphs.md
docs/src/DrawingGraphs.md
docs/src/GraphData.md
test/testFurther.jl

Fix documenter build/deploy

---

src/Deprecated.jl
src/entities/DFGVariable.jl

Fix inferdim->infoPerCoord bug and Escalate inferdim depwarn to error

---

src/CloudGraphsDFG/services/CommonFunctions.jl

- Fixes #857
Will need to cherry-pick into master.

Changed error to use defined arg

---

src/Neo4jDFG/services/CommonFunctions.jl

Forward port of fixes in DFG v0.17.1

---

Project.toml
src/Common.jl
src/Neo4jDFG/services/CGStructure.jl
src/Neo4jDFG/services/CommonFunctions.jl
src/Neo4jDFG/services/Neo4jDFG.jl
test/CGStructureTests.jl
test/iifInterfaceTests.jl
test/interfaceTests.jl
test/runtests.jl
test/testBlocks.jl

Defensively implementing backticks on sentinel nodes (userId, robotId, sessionId)

---

src/GraphsDFG/services/GraphsDFG.jl
src/LightDFG/services/LightDFG.jl
src/Neo4jDFG/services/Neo4jDFG.jl
src/services/AbstractDFG.jl

add detail kw to getVariables

---

Project.toml
src/DataBlobs/entities/AbstractDataEntries.jl
src/FileDFG/services/FileDFG.jl
src/services/Serialization.jl

serialize DFGVariable top level JSON only

---

src/entities/DFGVariable.jl

Fix VariableNodeData constructor

---

src/services/CustomPrinting.jl

show on var entries, 

---

src/DataBlobs/entities/AbstractBlobEntries.jl
src/DataBlobs/services/AbstractBlobEntries.jl
src/DataBlobs/services/BlobEntry.jl
src/DataBlobs/services/BlobStores.jl
src/Deprecated.jl
src/entities/AbstractDFG.jl
src/entities/DFGVariable.jl
src/services/Serialization.jl
test/interfaceTests.jl

drop AbstractBlobEntry

---

src/entities/DFGVariable.jl

Adding covar to PackedVND

---

src/DataBlobs/services/BlobEntry.jl
src/DataBlobs/services/HelpersDataWrapEntryBlob.jl
src/DistributedFactorGraphs.jl

convenience function for gathering many blob entries over variables

new getBlobEntriesVariables

---

.github/workflows/ci.yml
Project.toml
ext/DFGPlots.jl
src/Common.jl
src/DistributedFactorGraphs.jl
src/services/AbstractDFG.jl
src/services/Serialization.jl

Use weakdeps; drop Requires and jl < v1.9 

---

src/DistributedFactorGraphs.jl
src/GraphsDFG/GraphsDFG.jl
src/GraphsDFG/services/GraphsDFG.jl
src/services/AbstractDFG.jl

list[User/Robot/Session]BlobEntries

---

src/GraphsDFG/services/GraphsDFG.jl

TODO: still need to be added to all relevant functions and tests.
close #222
close #331

solvableFilter on listVariables and getVariables for GraphsDFG
